name: Publish to GitHub Packages

on:
  push:
    branches: 'feature/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: 1.8
    
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Grant execute permission for gradle
      run: chmod +x ./gradlew
      working-directory: android

    - name: Grant execute permission for script
      run: chmod +x ./upload_github.sh
      working-directory: android

    - name: Run Script
      env:
        GH_PACKAGES_TOKEN: ${{ secrets.TOKEN }}
      run: ./upload_github.sh
      working-directory: android