name: Publish to GitHub Packages

on:
  push:
    branches: 'feature/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Grant execute permission for gradle
      run: chmod +x ./gradlew
      working-directory: android

    - name: Grant execute permission for script
      run: chmod +x ./upload_github.sh
      working-directory: android

    - name: Run Script
      env:
        GH_PACKAGES_TOKEN: ${{ secrets.TOKEN }}
      run: ./upload_github.sh
      working-directory: android